name: "configure-nix-action test"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  simple-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - name: Configure Nix
        uses: ./
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - run: cat $HOME/.config/nix/nix.conf
      - run: cat $HOME/.config/nix/netrc
      - run: nix-build test.nix

  custom-nix-path:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - name: Configure Nix
        uses: ./
        with:
          nix_path: nixpkgs=channel:nixos-23.05
      - run: test $NIX_PATH == "nixpkgs=channel:nixos-23.05"
      - run: nix-build test.nix

  extra-nix-config:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - name: Configure Nix
        uses: ./
        with:
          nix_path: nixpkgs=channel:nixos-22.11
          extra_nix_config: |
            sandbox = relaxed
      - run: cat $HOME/.config/nix/nix.conf
      - run: nix-build test.nix --arg noChroot true

  flakes:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - name: Configure Nix
        uses: ./
      - run: nix flake show github:numtide/treefmt
      - run: nix flake show github:numtide/private-test-flake